# Generated by Django 4.2.2 on 2023-06-08 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_category',
            fields=[
                ('PCid', models.IntegerField(primary_key=True, serialize=False)),
                ('PCname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('Pid', models.IntegerField(primary_key=True, serialize=False)),
                ('Pname', models.CharField(max_length=100)),
                ('Pprice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Pdescription', models.CharField(max_length=100)),
                ('Pdate', models.DateField()),
                ('PCname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product_category')),
            ],
        ),
    ]
